In [68]:
import numpy as np

In [69]:
list = [1,2,3,4,5]

In [70]:
ar = np.array(list)

In [72]:
ar.dtype

dtype('int32')

In [17]:
ar + 3 * ar

array([ 4,  8, 12, 16, 20])

In [58]:
ar * ar

array([ 1,  4,  9, 16, 25])

In [18]:
list + 3 * list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [19]:
list + list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [20]:
type(ar)

numpy.ndarray

# 多维数组

In [51]:
ar2 = np.array([(1,2,3),
                (4,5,6)]
              )

In [52]:
ar3 = np.array([[1,2,3],
               [4,5,6]]
              )

In [53]:
ar4 = np.array([[1,4],
                [2,5],
                [3,6]]
              )

In [54]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
ar3

array([[1, 2, 3],
       [4, 5, 6]])

### 对应元素相乘

In [56]:
ar2 * ar3

array([[ 1,  4,  9],
       [16, 25, 36]])

In [57]:
ar2 * ar4

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [3]:
L = list(range(1,5))

In [14]:
A = np.array(    list(range(1,5))    )

In [15]:
A

array([1, 2, 3, 4])

# 初始化一个list

In [27]:
val = 0
len = 5
l = [val for i in list(range(len))]   # 生成列表
print(l)

[0, 0, 0, 0, 0]


In [21]:
ll = [m+n for m in "ABC" for n in "123"]
print(ll)

['A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'C1', 'C2', 'C3']


In [28]:
l.append(3)

In [29]:
l

[0, 0, 0, 0, 0, 3]

In [33]:
if 3 in l:
    del l[l.index(3)]

In [34]:
l

[0, 0, 0, 0, 0]

In [49]:
d = {1:'a',2:'b',3:'c'}

In [37]:
d.keys()

dict_keys([1, 2, 3])

In [38]:
d.values()

dict_values(['a', 'b', 'c'])

In [39]:
d.items()

dict_items([(1, 'a'), (2, 'b'), (3, 'c')])

In [54]:
for (x,y) in d.items():
    if x == 3 or y == 'a':
        d[x] = 99

### 使用占位符

In [66]:
print ("%s is %d"   %("one",1))

one is 1


### 强制类型指定

In [77]:
arr = np.array([1,2,3],dtype = complex)
print(arr)

[ 1.+0.j  2.+0.j  3.+0.j]


In [87]:
arr1 = np.zeros((3,4),dtype = int)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [88]:
arr2 = np.arange(10,30,5)

In [94]:
arr3 = np.linspace(-1, 0, 5)

In [95]:
arr3

array([-1.  , -0.75, -0.5 , -0.25,  0.  ])

In [97]:
arr = np.array([1,2,3],dtype = np.int32)

In [99]:
arr.reshape(3,1)

array([[1],
       [2],
       [3]])