In [15]:
import pandas as pd
import numpy as np
import time
import sys

In [16]:
a = ['_']*6

In [17]:
a

['_', '_', '_', '_', '_', '_']

In [18]:
print(a)

['_', '_', '_', '_', '_', '_']


In [19]:
def main():
    for i in range(65,91):
        s="\r{name:s}".format(name=chr(i))
        time.sleep(0.5)
        sys.stdout.write(s)
 
main()

Z

In [20]:
episode = 8
step_counter = 19
interaction = 'Episode %s: total_steps = %s' % (episode+1, step_counter)

In [21]:
interaction

'Episode 9: total_steps = 19'

In [22]:
type(interaction)

str

AttributeError: 'str' object has no attribute 'dtype'

In [28]:
S = 1
episode = 8
step_counter = 19
FRESH_TIME = 2
env_list = ['-']*(8-1) + ['T']   # '---------T' our environment
if S == 'terminal':
    interaction = 'Episode %s: total_steps = %s' % (episode+1, step_counter)
    print('\r{}'.format(interaction), end='')
    time.sleep(2)
    print('\r                                ', end='')
else:
    env_list[S] = 'o'
    interaction = ''.join(env_list)
    print('\r{}'.format(interaction), end='')
    time.sleep(FRESH_TIME)

-o-----T

In [32]:
S = 4
env_list[S] = 'o'
interaction = ''.join(env_list)
print('\r{}'.format(interaction), end='')
time.sleep(FRESH_TIME)

-o--o--T

In [35]:
env_list[S]

'o'

In [37]:
print(interaction)

-o--o--T


In [ ]:
def build_q_table(coor, actions):
    table = pd.DataFrame(        np.zeros(   (   n_states, len(actions)   )    ),
        columns=actions,    # actions's name
    )
    print(table)    # show table
    return table

In [45]:
a = np.zeros((2,2,5), dtype = np.int32)

In [46]:
print(a)

[[[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]]


In [47]:
a[1,1,1]

0

In [49]:
a[0,0,4]

0

In [51]:
len(8)

TypeError: object of type 'int' has no len()

In [126]:
# Define q Table
def build_q_table(coor, actions):
    tmp = coor
    tmp.append(len(actions))
    table = np.zeros(tmp) # q_table initial values
    #print(table)    # show table
    return table

In [129]:
ACTIONS = ['up','down','left', 'right']
t  = build_q_table([4,4], ACTIONS)

In [130]:
t

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [183]:
EPSILON = 0.9
# Define how to choose an action
def choose_action(coor, q_table):
    state_actions = q_table[coor[0], coor[1], :]       #[0, 0, 0, 0]
    if (np.random.uniform() > EPSILON) or ((state_actions == 0).all()): 
        action_name = np.random.choice(ACTIONS)
    else:   # act greedy
        index = state_actions.index(max(state_actions))
        action_name = ACTIONS[index]
    return action_name

In [184]:
choose_action([2,2], t)

<class 'list'>


AttributeError: 'bool' object has no attribute 'all'

In [163]:
def getIndex(A):
    if A == 'up':
        return 0
    if A == 'down':
        return 1
    if A == 'left':
        return 2
    if A == 'right':
        return 3

In [164]:
getIndex('up')

0

In [165]:
t

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [167]:
t[2,2,:].max()

0.0

In [9]:
a = ["2"]
a*3

['2', '2', '2']

In [10]:
a = [2,3]
a*3

[2, 3, 2, 3, 2, 3]

In [11]:
import numpy as np

In [14]:
a1 = np.tile(a,3)

In [15]:
a1

array([2, 3, 2, 3, 2, 3])

In [27]:
b = np.zeros([3,2])
b

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [28]:
for i in range(3):
    b[i, :] = a

In [29]:
b

array([[ 2.,  3.],
       [ 2.,  3.],
       [ 2.,  3.]])

In [30]:
b[1]

array([ 2.,  3.])

In [1]:
import tensorflow as tf

C:\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
