In [1]:
import random as rd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
lst = [1.1, 2.2, 3.3, 4.4, 5.5]
ar = np.array(lst)

In [17]:
print(ar.dtype)
print(ar)
ar = ar.astype(np.int32)
print(ar)

float64
[1.1 2.2 3.3 4.4 5.5]
[1 2 3 4 5]


In [30]:
ar1 = np.array([[1,1,1],[2,2,2],[3,3,3]])
print (ar1)
ar2 = np.array([[2,2,2],[3,3,3],[1,1,1]])
print(ar2)
print('对应位置相乘\n',ar1*ar2)
print('矩阵相乘\n',np.dot(ar1,ar2))
print(ar1/ar2)
print(np.divide(ar1,ar2))

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[2 2 2]
 [3 3 3]
 [1 1 1]]
对应位置相乘
 [[2 2 2]
 [6 6 6]
 [3 3 3]]
矩阵相乘
 [[ 6  6  6]
 [12 12 12]
 [18 18 18]]
[[0.5        0.5        0.5       ]
 [0.66666667 0.66666667 0.66666667]
 [3.         3.         3.        ]]
[[0.5        0.5        0.5       ]
 [0.66666667 0.66666667 0.66666667]
 [3.         3.         3.        ]]


In [1]:
import glob
import pickle

glob.glob('*.pickle')

['pickle_example.pickle', 'usrs_info.pickle']

In [5]:
with open('usrs_info.pickle', 'rb') as f:
    x = pickle.load(f)
print(x)

{'admin': 'admin', 'bridge@python.com': '1535'}
